<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>NeoSwitch</AssemblyName>
    <RootNamespace>NeoSwitch.App</RootNamespace>
    <ApplicationIcon />
    <UseWPF>false</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NeoSwitch.Core\NeoSwitch.Core.csproj" />
  </ItemGroup>

</Project>
